# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/tommy351/hexo/

# Site
title: Cup Full of Code
subtitle:
description: The personal site of Matthew M. Keeler
author: Matthew Keeler
email: keelerm@tortugas-llc.com
language: en

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://cupfullofcode.com
root: /
permalink: blog/:year/:month/:day/:title/
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code

# Directory
source_dir: source
public_dir: public

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
auto_spacing: false # Add spaces between asian characters and western characters
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
max_open_file: 100
multi_thread: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
highlight:
  enable: true
  line_number: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 2
category: 2
tag: 2

# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
server_ip: 0.0.0.0
logger: false
logger_format:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMM D YYYY
time_format: H:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 6
pagination_dir: page

# Disqus
disqus_shortname: cupfullofcode

# Extensions
## Plugins: https://github.com/tommy351/hexo/wiki/Plugins
## Themes: https://github.com/tommy351/hexo/wiki/Themes
theme: escape-velocity
exclude_generator:

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: github
  repo: https://github.com/keelerm84/cupfullofcode.com.git
  branch: gh-pages

feed:
  type: atom
  path: atom.xml
  limit: 20

alias:
  a-note-on-recovering-from-innodb-corruption/: http://jacob-walker.com/blog/a-note-on-recovering-from-innodb-corruption.html
  regular-expressions-101/: http://jacob-walker.com/blog/regular-expressions-101.html
  spf13-vim-the-ultimate-vim-distribution/: http://jacob-walker.com/blog/spf13-vim.html
  php-clone-and-shallow-vs-deep-copying/: http://jacob-walker.com/blog/php-clone-and-shallow-vs-deep-copying.html
  invalidate-projectile-cache-on-delete/: blog/2014/10/06/invalidate-projectile-cache-on-delete/
  performing-controlled-php-refactorings-in-emacs/: blog/2014/09/21/php-refactor-mode/
  generate-daily-messages-with-org-journal/: blog/2013/11/17/daily-messages-with-org-journal/
  embedding-code-snippets-in-org-mode/: blog/2013/11/22/embedding-code-snippets-in-org-mode/
  efficient-command-line-navigation/: blog/2013/07/03/efficient-command-line-navigation/
  git-from-init-through-commit/: /
  snippet-expansion-with-yasnippet/: blog/2013/02/26/snippet-expansion-with-yasnippet/
  automation-with-gnu-screen-and-ssh/: blog/2013/01/08/automation-with-gnu-screen-and-ssh/
  dancing-code-monkey/: blog/2013/01/05/dancing-code-monkey/

