baseurl = "https://cupfullofcode.com"
title = "Cup Full of Code"

theme = "fuji"
hasCJKLanguage = true
enableEmoji = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

## Change this two to switch between different language
languageCode = "en"           # For RSS, view https://www.rssboard.org/rss-language-codes
defaultContentLanguage = "en" # For HTML page, now support: en, zh-hans, zh-hant, ja, nl, pl, it

summaryLength = 100 # Custom summary length, add <!--more--> in post file to custom split point
paginate = 5

preserveTaxonomyNames = false
disqusShortname = "cupfullofcode"
googleAnalytics = "UA-55725869-1"
pluralizeListTitles = false

# Set the followings to true as part of your site SEO
enableRobotsTXT = true
canonifyURLs = true

mainSections = ["blog"]

[outputFormats]
[outputFormats.SearchIndex]
isPlainText = true
notAlternative = true
mediaType = "application/json"
path = "/search/"

[outputs]
home = ["HTML", "RSS", "SearchIndex"]

[permalinks]
blog = "/blog/:year/:month/:day/:title"

[params]
author = "Matthew M. Keeler"
subTitle = "The personal site of Matthew M. Keeler"
navbarTitle = "Cup Full of Code"
sourceURL = "https://github.com/keelerm84/cupfullofcode.com"

# options for highlight.js (version, additional languages, and theme)
disable_highlight = false # set to true to disable Highlight
highlightjsVersion = "9.12.0"
highlightjsCDN = "https://cdnjs.cloudflare.com/ajax/libs/"
highlightjsLang = ["lisp"]
highlightjsTheme = "gruvbox-dark"
MathJaxCDN = "//cdn.bootcss.com"
MathJaxVersion = "2.7.1"

showWordCounter = true
showReadTime = true
showLicenseInFooter = false
showToc = true

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true # Enable user to embed HTML snippets in Markdown content
[markup.highlight]
codeFences = false # Disable Hugo's code highlighter

[markup.tableOfContents]
startLevel = 2
endLevel = 3

[taxonomies]
tag = "tags"

[menu]
[[menu.nav]]
name = "Home"
url = "/"
weight = 1
[[menu.nav]]
name = "About"
url = "/about/"
weight = 2
[[menu.nav]]
name = "Blog"
url = "/blog/"
weight = 3
[[menu.nav]]
name = "Search"
url = "/search/"
weight = 4
[[menu.nav]]
name = "RSS"
url = "/index.xml"
weight = 5

[[menu.link]]
name = "GitHub"
url = "https://github.com/keelerm84"
weight = 1
[[menu.link]]
name = "Twitter"
url = "https://twitter.com/keelerm84"
weight = 2

[build]
noJSConfigInAssets = true

[security]
enableInlineShortcodes = true

# Disqus will take priority over Staticman (github.com/eduardoboucas/staticman)
# due to its ease of use. Feel free to check out both and decide what you would
# prefer to use. See Staticman.yml for additional settings.
[params.staticman]
  # Sets Statiman to be active
  staticman = false
  # Sets the location for Staticman to connect to
  username  = ""
  repo      = ""
  branch    = ""

  [params.staticman.recaptcha]
    sitekey = "SITE_KEY"
    secret  = "ENCRYPTED_SECRET"
