# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More

# Sidebar
sidebar: right
widgets:
- category

# Miscelaneous
favicon: /favicon.png

less:
  paths:
    - source/css